name: CI Build

#
# This is a generic CI pipeline that assumes project is to be built as a container image
# Note. CI build only builds 'latest' image, not a versioned release
# Note. IMAGE_SECRET must be set

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE_REG: ghcr.io
  IMAGE_NAME: changeme
  IMAGE_TAG: latest

jobs:
  ci-build:
    name: Code Check & CI build
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repo
      - name: Checkout repo
        uses: actions/checkout@v2

      # Validate code
      - name: Check code for linting and format errors
        run: make lint

      # Build image
      - name: Build the container image
        run: make image IMAGE_REPO=$GITHUB_ACTOR/$IMAGE_NAME

      # Only when pushing to master push to IMAGE_REG
      - name: Push to container registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.IMAGE_SECRET }} | docker login $IMAGE_REG -u $GITHUB_ACTOR --password-stdin
          make push
